### PR TITLE
 Introduce additional_locales option

### PR DESCRIPTION
**Pull request by dirkholzapfel**
This option allows us to whitelist locales that are not defined via Gettext. Possible scenario: You want to use Gettext and some client side SaaS localization service (e.g. http://bablic.com/) in parallel. Whitelisting these additional languages allows you to have proper routing for the locales and trigger the wanted JS behaviour depending on the assigned locale in your templates.

### CODE REVIEW

**Comment by dirkholzapfel** [comment]
Found a bug in this code while testing on staging. Will improve and reopen PR.

**Comment by dirkholzapfel** [comment]
Sorry for the buzz. The bug is unrelated to this PR and is existing in master as well. Will come with another PR soon.
for reference: set_locale fails when requesting `/?locale=valid_locale`as it does not redirect

**Comment by smeevil** [comment]
Sorry for the late response !

**Comment by smeevil** [comment]
0.2.8 has been published :D

**Pull request merged**
