### PR TITLE
fallback support to language from full language tags in accept-header

### PR DESCRIPTION
**Pull request by dirkholzapfel**
adds fallback to "nl" if "nl-nl" is given in accept-header

### CODE REVIEW

**Comment by dirkholzapfel** [comment]
sorry, i have to update the PR. there is one glitch left...

**Comment by dirkholzapfel** [comment]
update done

**Comment by smeevil** [comment]
Nice, thanks for your time :D

**Comment by smeevil** [comment]
just published 0.2.3 :)

**Comment by dirkholzapfel** [comment]
supercool, thx!

**Pull request merged**
